# Generated by Django 2.2.3 on 2019-07-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('申购时间', models.DateTimeField()),
                ('零件名称', models.CharField(max_length=30)),
                ('设备名', models.CharField(max_length=30)),
                ('资产类型', models.CharField(max_length=10)),
                ('型号', models.CharField(max_length=30)),
                ('品牌', models.CharField(max_length=10)),
                ('详细细节', models.CharField(max_length=30)),
                ('数量', models.IntegerField(max_length=10)),
                ('单位', models.CharField(max_length=5)),
                ('用途', models.CharField(max_length=30)),
                ('采购人', models.CharField(max_length=8)),
                ('申购人', models.CharField(max_length=8)),
                ('是否紧急', models.BooleanField()),
                ('图片', models.BinaryField()),
            ],
        ),
    ]
