# Generated by Django 2.2.3 on 2019-07-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spares', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spare',
            name='数量',
            field=models.IntegerField(),
        ),
    ]
