# Generated by Django 2.2.3 on 2019-07-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spares', '0002_auto_20190720_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spare',
            name='图片',
            field=models.ImageField(upload_to=''),
        ),
    ]
