# Generated by Django 2.2.3 on 2019-07-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spares', '0005_auto_20190720_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spare',
            name='申购时间',
            field=models.DateField(),
        ),
    ]
