# Generated by Django 2.2.3 on 2019-07-20 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spares', '0006_auto_20190721_0124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spare',
            old_name='是否紧急',
            new_name='是否即用',
        ),
    ]
