# Generated by Django 2.2.3 on 2019-07-20 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spares', '0007_auto_20190721_0129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spare',
            old_name='是否即用',
            new_name='即用or备用',
        ),
        migrations.RenameField(
            model_name='spare',
            old_name='图片',
            new_name='是否有图片附件',
        ),
    ]
