# Generated by Django 2.2.3 on 2019-07-20 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spares', '0009_auto_20190721_0137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spare',
            old_name='即用\\备用',
            new_name='即用备用',
        ),
    ]
