# Generated by Django 2.2.3 on 2019-07-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spares', '0010_auto_20190721_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spare',
            name='即用备用',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='spare',
            name='是否有图片附件',
            field=models.CharField(max_length=5),
        ),
    ]
